# Generated by Django 5.2 on 2026-07-30 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        ('ui_automation', '0006_merge_uimodule_order_and_db2_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UiElementMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='地图名称')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('base_url', models.TextField(blank=True, null=True, verbose_name='基础 URL')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('map_json', models.JSONField(blank=True, default=dict, verbose_name='元素地图')),
                ('coverage_summary', models.JSONField(blank=True, default=dict, verbose_name='覆盖统计')),
                ('low_confidence_items', models.JSONField(blank=True, default=list, verbose_name='低置信度元素')),
                ('risk_items', models.JSONField(blank=True, default=list, verbose_name='高风险入口')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_ui_element_maps', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ui_element_maps', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('environment_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_maps', to='ui_automation.uienvironmentconfig', verbose_name='环境配置')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_element_maps', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI 元素地图',
                'verbose_name_plural': 'UI 元素地图',
                'db_table': 'ui_element_map',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UiAiGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('source_type', models.CharField(choices=[('natural_language', '自然语言'), ('gherkin', 'Gherkin'), ('testcase', '测试用例'), ('requirement', '需求')], default='natural_language', max_length=32, verbose_name='来源类型')),
                ('source_requirement', models.TextField(blank=True, null=True, verbose_name='自然语言需求')),
                ('gherkin', models.TextField(blank=True, null=True, verbose_name='Gherkin')),
                ('target_url', models.TextField(blank=True, null=True, verbose_name='目标 URL')),
                ('target_module', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标模块')),
                ('safety_policy', models.JSONField(blank=True, default=dict, verbose_name='安全边界策略')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('actuator_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='执行器 ID')),
                ('test_plan', models.JSONField(blank=True, default=dict, verbose_name='测试计划')),
                ('mcp_observations', models.JSONField(blank=True, default=list, verbose_name='MCP 观察记录')),
                ('element_map_snapshot', models.JSONField(blank=True, default=dict, verbose_name='元素地图快照')),
                ('generated_case', models.JSONField(blank=True, default=dict, verbose_name='生成的执行步骤')),
                ('generated_script', models.TextField(blank=True, null=True, verbose_name='生成的 Playwright 脚本')),
                ('generated_script_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='脚本 Hash')),
                ('verification_result', models.JSONField(blank=True, default=dict, verbose_name='验证结果')),
                ('repair_history', models.JSONField(blank=True, default=list, verbose_name='修复历史')),
                ('failure_category', models.CharField(blank=True, choices=[('', '未分类'), ('locator', '定位失败'), ('timeout', '等待超时'), ('assertion', '断言失败'), ('data', '测试数据问题'), ('permission', '权限问题'), ('environment', '环境问题'), ('product_defect', '产品缺陷'), ('llm', 'LLM 生成问题'), ('unknown', '未知问题')], default='', max_length=32, verbose_name='失败分类')),
                ('max_repair_rounds', models.PositiveSmallIntegerField(default=2, verbose_name='最大修复轮数')),
                ('current_repair_round', models.PositiveSmallIntegerField(default=0, verbose_name='当前修复轮数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ui_ai_generation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('environment_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_tasks', to='ui_automation.uienvironmentconfig', verbose_name='环境配置')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_ai_generation_tasks', to='projects.project', verbose_name='所属项目')),
                ('element_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_tasks', to='ui_automation.uielementmap', verbose_name='元素地图')),
            ],
            options={
                'verbose_name': 'AI UI 生成任务',
                'verbose_name_plural': 'AI UI 生成任务',
                'db_table': 'ui_ai_generation_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
