# Generated by Codex on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0007_uielementmap_uiaigenerationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiaigenerationtask',
            name='dispatch_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='最近分发 ID'),
        ),
        migrations.AddField(
            model_name='uiaigenerationtask',
            name='dispatch_status',
            field=models.CharField(
                choices=[
                    ('pending', '待下发'),
                    ('sent', '已下发'),
                    ('acked', '已入队'),
                    ('duplicate', '重复入队'),
                    ('completed', '已完成'),
                    ('failed', '下发失败'),
                ],
                default='pending',
                max_length=20,
                verbose_name='分发状态',
            ),
        ),
        migrations.AddField(
            model_name='uiaigenerationtask',
            name='dispatch_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='分发次数'),
        ),
        migrations.AddField(
            model_name='uiaigenerationtask',
            name='last_dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近下发时间'),
        ),
        migrations.AddField(
            model_name='uiaigenerationtask',
            name='last_ack_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近 ACK 时间'),
        ),
        migrations.AddField(
            model_name='uiaigenerationtask',
            name='last_dispatch_error',
            field=models.TextField(blank=True, null=True, verbose_name='最近分发错误'),
        ),
    ]
