# Generated by Codex on 2026-08-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0008_ai_generation_dispatch_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='uielementmap',
            name='parent_map',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='derived_versions',
                to='ui_automation.uielementmap',
                verbose_name='父版本地图',
            ),
        ),
        migrations.AddField(
            model_name='uielementmap',
            name='version_group',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='版本组'),
        ),
        migrations.AddField(
            model_name='uielementmap',
            name='role_key',
            field=models.CharField(blank=True, default='default', max_length=128, verbose_name='角色标识'),
        ),
        migrations.AddField(
            model_name='uielementmap',
            name='permission_key',
            field=models.CharField(blank=True, default='default', max_length=128, verbose_name='权限标识'),
        ),
        migrations.AddField(
            model_name='uielementmap',
            name='map_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='地图 Hash'),
        ),
        migrations.AddField(
            model_name='uielementmap',
            name='baseline_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='定位基线 Hash'),
        ),
        migrations.AddField(
            model_name='uielementmap',
            name='diff_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='版本差异摘要'),
        ),
        migrations.AddField(
            model_name='uielementmap',
            name='stale_status',
            field=models.CharField(blank=True, default='current', max_length=20, verbose_name='过期状态'),
        ),
        migrations.AddField(
            model_name='uielementmap',
            name='stale_reason',
            field=models.TextField(blank=True, default='', verbose_name='过期原因'),
        ),
    ]
